### ISSUE TITLE
Rhel/Centos 8 versionlock doesn't work

### ISSUE THREAD

**Issue by AlexSamad** [voxpupuli/puppet-yum#150]
Seems like the format of the file has changed in Centos 8

I have to configure like so 
yum::versionlock { '1:java-1.8.0-openjdk-headless-1:1.8.0.232.b09-0.el8_0.*':
    ensure => present,
  }

but the line should be

yum::versionlock { 'java-1.8.0-openjdk-headless-1:1.8.0.232.b09-0.el8_0.*':
    ensure => present,
  }

But the module balks at that !

**Comment by TJM** [comment]
I have noticed that the module is fairly cranky about the formatting, way more cranky than yum itself, even on EL7 :)

**Comment by vykulakov** [comment]
The current approach with editing the lock file directly looks not so robust and leads to incorrect behaviour in some cases (at least in my cases). Why doesn't it use a command-line interface of the yum version lock plugin? Like the install command and others. Maybe, it's worth to rewrite this component to use command-line interface as well?

**Comment by TJM** [comment]
I think it would be a great idea! A type and provider would allow the plugin to be agnostic to the actual contents of the configuration file.  In addition to the "ensure => present" -> add and "ensure => absent" -> delete (and possibly some sort of exclude capability), I would recommend supporting a generic "options" for the various command line flags.

~tommy

PS: I have honestly always thought that the package provider should automatically "versionlock" a package when someone sets a "version" for the ensure parameter, rather than "present" ... I wonder how hard it would be to add that capability?

**Comment by vykulakov** [comment]
I've checked the approaches with editing the lock file (the current one) and with invoking the yum version lock command directly (the supposed one) and for me, it looks impossible to use the second approach because the approaches lock packages in different ways:
1. yum can lock only available/installed packages
2. yum lock only packages that are available at the moment of locking. If we use a template for locking, yum matches all available packets with it and locks matched ones. If we will have a new package in a repository for the template, it won't be locked.
These differences may spoil people's Puppet configuration and lead to unexpected things. So it will be better to not change anything.

**Comment by vykulakov** [comment]
@AlexSamad 
BTW the plugin does not support CentOS 8 at all. So it is expected that you have some problems with it on CentOS 8 and it would be better to name the issues like "Add CentOS 8 support".

**Comment by marszip** [comment]
According to the latest compatible versions on the Puppetforge site RHEL8 should be supported, but this issue is still present. We would like to use this feature so a solution would be much appreciated.

**Comment by vchepkov** [comment]
I have encountered it too, python3-dnf-plugin-versionlock changed the format
https://dnf-plugins-core.readthedocs.io/en/latest/versionlock.html
```
%{NAME}-%{EPOCH}:%{VERSION}-%{RELEASE}.%{ARCH}
```
